```yaml
---
plugin: ansible.builtin.constructed
hosts:
  k8s_nodes:
    hosts: "{{ node_ips }}"
compose:
  ansible_host: "{{ inventory_hostname }}"
vars:
  terraform_output: "{{ lookup('file', 'terraform_output.json') | from_json }}"
  node_ips: "{{ terraform_output[terraform_output_key].value }}"
  terraform_output_key: "{{ lookup('env', 'TERRAFORM_OUTPUT_KEY') | default('node_ips', true) }}"
```
