```yaml
name: Deploy IaC and CaC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: policy-security
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # Install Ansible
      - name: Install Ansible
        run: |
          pip install ansible

      # Apply Terraform
      - name: Apply Terraform
        run: |
          terraform init
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Run Ansible playbook
      - name: Run Ansible playbook
        run: |
          ansible-playbook -i inventory.yml playbook.yml
        env:
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
```