```yaml
name: Validate IaC and CaC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # Install Ansible
      - name: Install Ansible
        run: |
          pip install ansible

      # Validate Terraform syntax
      - name: Validate Terraform
        run: |
          terraform init
          terraform validate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Validate Ansible playbook syntax
      - name: Validate Ansible playbook
        run: |
          ansible-playbook playbook.yml --syntax-check
```